### PR TITLE
Add external data checker

### LINKED ISSUE #3: Automate the update
We probably can use the flathub external data checker once it's in place instead of having our own thing here.

### PR DESCRIPTION
**Pull request by tilosp**
Depends on https://github.com/flathub/flatpak-external-data-checker/pull/93

Closes #3

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Thanks a lot for your work on this! I will see about getting the checker merged :)

**Comment by bilelmoussaoui** [comment]
Do you mind rebasing this one & updating it if needed?

**Comment by bilelmoussaoui** [comment]
It also needs an update to the flathub.json https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable/blob/branch/20.08/flathub.json to automatically merge the bot's PR if they succeed

**Comment by tilosp** [comment]
@bilelmoussaoui i rebased and added `automerge-flathubbot-prs`

**Comment by bilelmoussaoui** [comment]
Thanks

**Pull request merged**
