### PR TITLE
Update runtime to 20.08

### PR DESCRIPTION
**Pull request by tim77**
Not sure should we create new branch or can simply move to latest and greatest FD runtime for Rust-nightly.

Fix: #7

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I would still keep 19.08 around for a while and make 20.08 the default branch.

**Comment by tim77** [comment]
Lets close this one PR and create a new branch. I can't create branches, only repo owners can do that.

**Comment by bilelmoussaoui** [comment]
You don't necessarily have to recreate the merge request, you can switch the targeted branch by editing the merge request. I've created a branch/20.08.

**Comment by tim77** [comment]
Let's merge it?
###### [/me ping in case if you missed email notification which happens with GH recent times]

**Pull request merged**
